config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy' #3件いずれも、URLの見栄え重視でresourcesを使わない。　resources :sessions, only: [:new, :create, :destroy]
  
  get 'signup', to: 'users#new' #下記でusers#newを設定しているにもかかわらずここで設定するのは、URLを/signupにするため。URLが/users/newだと少々不恰好。
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  
  resources :microposts, only: [:create, :destroy]  #do #microposts単独でのshowは必要ない。userに紐づいており、(一覧)表示するにしてもそちらでするため。
=begin
    member do
      get :attracteds
    end
  end
=end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :favorites, only: [:create, :destroy]

end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user #この関連付けにより、Micropostモデルのインスタンス内でインスタンスメソッドuserが使用可能。そのmicropostインスタンスの紐づくuserインスタンスを取得できる。
                   #同時に、Userモデルのrubyファイルで規定したhas_manyにより、特定のuserインスタンスでmicropostsメソッド実行により、そのインスタンスに紐づく全投稿を取得できる。  
  validates :content, presence: true, length: { maximum: 255 }
  
  has_many :favorites, dependent: :destroy
#  has_many :attracteds, through: :favorites, source: :user
  
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def create
    @micropost = current_user.microposts.build(micropost_params) # Micropost.newの代わり
    if @micropost.save
      flash[:success] = 'メッセージを投稿しました。'
      redirect_to root_url
    else
      @microposts = current_user.feed_microposts.order(id: :desc).page(params[:page])
      flash[:danger] = 'メッセージの投稿に失敗しました。'
      render 'toppages/index'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end
=begin
  def attracteds
    @users = Micropost.find(params[:id]).attracteds.order(created_at: :desc).page(params[:page])
  end
=end  
  private
  def micropost_params
    params.require(:micropost).permit(:content)
  end
  
  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    unless @micropost
      redirect_to root_url
    end
  end
end

app/views/microposts/_microposts.html.erb
<ul class="list-unstyled">
  <% microposts.each do |micropost| %>
    <li class="media mb-3">
      <img class="mr-2 rounded" src="<%= gravatar_url(micropost.user, { size: 50 }) %>" alt="">
      <div class="media-body">
        <div>
          <%= link_to micropost.user.name, user_path(micropost.user) %> <span class="text-muted">posted at <%= micropost.created_at %></span>
        </div>
        <div>
          <p class="mb-0"><%= micropost.content %></p>
        </div>
        <div class="btn-toolbar">
          <div class="btn-group">
            <% if current_user == micropost.user %>
              <%= link_to "Delete", micropost, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
            <% end %>
          </div>
          <div class="btn-group">
            <%= render 'favorites/like_button', micropost: micropost %>
          </div>
          <!--
          <div class="btn-group">
            <%# link_to 'Users who like this post', attracteds_micropost_path(micropost), class: 'btn btn-secondary btn-sm' %>
          </div>
          -->
        </div>
      </div>
    </li>
  <% end %>
  
  <%= paginate microposts %>
</ul>

app/views/microposts/attracteds.html.erb
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <ul class="list-unstyled">
      <% @users.each do |user| %>
        <li class="media mb-3">
          <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
          <div class="media-body">
            <div>
              <%= link_to user.name, user_path(user) %>
            </div>
            <%= render 'relationships/follow_button', user: user %>
          </div>
        </li>
      <% end %>
      
    <%= paginate @users %>
    </ul>
  </div>
</div>

app/views/microposts/create.html.erb
<h1>Microposts#create</h1>
<p>Find me in app/views/microposts/create.html.erb</p>

app/views/microposts/destroy.html.erb
<h1>Microposts#destroy</h1>
<p>Find me in app/views/microposts/destroy.html.erb</p>